version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  pre_build:
    commands:
      - echo Restore dependencies
      - dotnet restore
  build:
    commands:
      - echo Build the project
      - dotnet build
      - echo Run tests
      - dotnet test

artifacts:
  files:
    - '**/*'
  discard-paths: yes
